name: main Branch CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: sudo apt install gcc make xorg libxext-dev libbsd-dev libcriterion-dev
    - name: install mlx
      run: |
        make -C ./libs/minilibx_linux
        cd ./libs/minilibx_linux
        sudo cp libmlx.a libmlx_*.a /usr/local/lib/
        sudo cp mlx.h /usr/local/include/
        sudo mkdir -p /usr/local/man/man3 /usr/local/man/man1
        sudo cp man/man1/mlx*.1 /usr/local/man/man1/
        sudo cp man/man3/mlx*.3 /usr/local/man/man3/
    - name: make
      run: make
