name: main Branch CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: sudo apt install gcc make xorg libxext-dev libbsd-dev libcriterion-dev
    - name: make
      run: make
    - name: make tests
      run: |
        make -C tests
        ./tests/tests.out